title: Hello, blog at GitHub Pages!
author: Драган Ћајић
email: cajic_dragan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Dedicated to Java EE set of specifications for creating Enterprise Applications
  using Java, Tomcat, Ant, Maven, GlassFish, ...
theme: minima

# social links
linkedin_username: dragancajic # DO NOT include the @ character, or else the build will fail!
github_username:  dragancajic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
